import type { Metadata } from 'next';
import { Saira } from 'next/font/google';
import { Header } from './components/Header';
import './globals.css';

const saira = Saira({
  weight: ['300', '400', '500', '600'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className='h-screen bg-gradient-to-b from-slate-50 to-slate-400 ' lang='en'>
      <body className={saira.className}>
        <Header />
        <div className='p-4' >
          {children}
        </div>
      </body>
    </html>
  );
}
